name: 彩票开奖结果抓取
on:
  schedule:
    # 北京时间 19:00-22:30 每5分钟运行一次/实际10分钟运行一次 (UTC 11:00-14:30)
    - cron: '*/5 11 * * *'  # UTC 11:00-11:59
    - cron: '*/5 12 * * *'  # UTC 12:00-12:59
    - cron: '*/5 13 * * *'  # UTC 13:00-13:59
    - cron: '0-30 14 * * *'  # UTC 14:00-14:30
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape-first:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    concurrency:
      group: ${{ github.workflow }}-first-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 设置时区
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: 安装 Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager
          
      - name: 运行第一个抓取脚本
        run: python scrapered.py
        env:
          TZ: Asia/Shanghai
          
      - name: 备份第一个脚本的结果
        run: |
          for file in lam.txt xam.txt hk.txt tc.txt; do
            if [ -f "$file" ]; then
              cp "$file" "${file%.*}_6htv.txt"
            fi
          done
          
      - name: 提交第一个脚本的更新
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *_6htv.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "更新开奖结果(6htv99) $(date '+%Y-%m-%d %H:%M:%S')" && git push)

  scrape-second:
    needs: scrape-first
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    concurrency:
      group: ${{ github.workflow }}-second-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 设置时区
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: 安装 Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager
          
      - name: 运行第二个抓取脚本
        run: python scraper.py
        env:
          TZ: Asia/Shanghai
          
      - name: 备份第二个脚本的结果
        run: |
          for file in lam.txt xam.txt hk.txt tc.txt; do
            if [ -f "$file" ]; then
              cp "$file" "${file%.*}_8800.txt"
            fi
          done
        
      - name: 提交第二个脚本的更新
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *_8800.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "更新开奖结果(48489) $(date '+%Y-%m-%d %H:%M:%S')" && git push)
        
      - name: 删除旧的工作流运行记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 100