services:
  - type: worker
    name: lottery-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scraper.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1" 