name: 彩票开奖结果抓取
on:
  schedule:
    # 北京时间 11:00-12:30 每10分钟运行一次 (UTC 03:00-04:30)
    - cron: '*/10 3-4 * * *'  # UTC 03:00-04:59
    - cron: '0-30/10 5 * * *'  # UTC 05:00-05:30
    # 北京时间 13:30-15:00 每10分钟运行一次 (UTC 05:30-07:00)
    - cron: '30-59/10 5 * * *'  # UTC 05:30-05:59
    - cron: '*/10 6-7 * * *'  # UTC 06:00-07:59
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 增加超时限制以避免过早终止

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装 Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: 安装 ChromeDriver
        uses: nanasess/setup-chromedriver@master

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager

      - name: 运行抓取脚本
        run: |
          chromedriver --version
          python scraper.py
        env:
          TZ: Asia/Shanghai  # 使用环境变量设置时区

      - name: 提交更新
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "自动更新开奖结果 $(date '+%Y-%m-%d %H:%M:%S')" && git push)

      - name: 删除旧的工作流运行记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 100
