name: 彩票one

on:
  schedule:
    - cron: '*/5 12-14 * * *'  # 北京时间 20:30-22:30 每5分钟运行一次 (UTC+8)
  workflow_dispatch:  # 允许手动触发
    inputs:
      reason:
        description: '运行原因'
        required: false
        default: '手动触发更新'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg2
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
    
    - name: 彩票数据抓取
      run: python scrapered.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update lottery results" && git push) 
