name: 彩票开奖结果抓取
on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 设置Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: 安装 Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: 安装 ChromeDriver
        uses: nanasess/setup-chromedriver@master
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager
          
      - name: 运行抓取脚本
        run: |
          # 启动 ChromeDriver
          chromedriver --version
          python scraper.py
        
      - name: 提交更新
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "更新开奖结果"
          git push
