name: Run Lottery Analysis Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '25-45 13 * * *'  # 每天UTC时间13:25到13:45之间运行（北京时间21:25到21:45）
  workflow_dispatch:  # 添加手动触发选项

# 定义工作流中的作业
jobs:
  analyze:  # 作业名称
    runs-on: ubuntu-latest  # 在最新版本的Ubuntu运行环境中运行

    steps:
    # 检出代码到运行环境
    - uses: actions/checkout@v2

    # 设置Python环境
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # 使用最新的Python 3版本

# 安装所需的Python依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

# 运行11美化开奖记录.sh脚本
    - name: Run 11美化开奖记录.sh
      run: sh 11美化开奖记录.sh

    # 运行12fenxi.sh脚本
    - name: Run 12fenxi.sh
      run: sh 12fenxi.sh

    # 提交并推送更改（如果有的话）
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --cached --exit-code || (git commit -m "Update lottery analysis results" && git push)
